spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tododb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jdbc:
    template:
      query-timeout: 5s
  sql:
    init:
      mode: always

server:
  port: 8080
